### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by iwallace1** [basespace/basespace-help#119]
The information on this page (https://help.basespace.illumina.com/articles/tutorials/switch-existing-account-to-new-credentials/) is incorrect.

ILMN Tech Support has confirmed with Customer Service that the username associated with an existing MyIllumina/BaseSpace account cannot be changed.

**Comment by greghroberts** [comment]
@iwallace1 you are correct, you can't change your username currently, but you can update your email.  We will update this in this article.  Thank you!
